export const CITIES_PRESETS = [
  { name: 'Москва', value: 'Москва\nMoscow\nМСК\nMsk' },
  { name: 'Санкт-Петербург', value: 'Санкт-Петербург\nСанкт\nSaint\nСПб\nSpb' },
  { name: 'Новосибирск', value: 'Новосибирск\nNovosibirsk\nНск\nNsk' },
  { name: 'Екатеринбург', value: 'Екатеринбург\nYekaterinburg\nЕкб\nEkb' },
  { name: 'Казань', value: 'Казань\nKazan\nКЗН\nKzn' },
  { name: 'Нижний Новгород', value: 'Нижний Новгород\nNizhny Novgorod' },
  { name: 'Челябинск', value: 'Челябинск\nChelyabinsk' },
  { name: 'Красноярск', value: 'Красноярск\nKrasnoyarsk' },
  { name: 'Самара', value: 'Самара\nSamara' },
  { name: 'Уфа', value: 'Уфа\nUfa' },
  { name: 'Ростов-на-Дону', value: 'Ростов-на-Дону\nRostov-on-Don\nРостов\nRostov' },
  { name: 'Омск', value: 'Омск\nOmsk' },
  { name: 'Краснодар', value: 'Краснодар\nKrasnodar' },
  { name: 'Воронеж', value: 'Воронеж\nVoronezh' },
  { name: 'Таганрог', value: 'Таганрог\nНиколаевка' },
  { name: 'Пермь', value: 'Пермь' },
  { name: 'Волгоград', value: 'Волгоград\nVolgograd' },
  { name: 'Саратов', value: 'Саратов\nSaratov' },
  { name: 'Тюмень', value: 'Тюмень\nTyumen' },
  { name: 'Тольятти', value: 'Тольятти\nTolyatti' },
  { name: 'Ижевск', value: 'Ижевск\nIzhevsk' },
  { name: 'Барнаул', value: 'Барнаул\nBarnaul' },
  { name: 'Иркутск', value: 'Иркутск\nIrkutsk' },
  { name: 'Хабаровск', value: 'Хабаровск\nKhabarovsk' },
  { name: 'Владивосток', value: 'Владивосток\nVladivostok' },
];
